### ISSUE TITLE
PhraseApp CLI is a false positive malware, according to Symantec

### ISSUE THREAD

**Issue by peterbetos** [phrase/phraseapp-client#120] opened 2018-04-05 18:14 UTC
We seem to receive a false positive on Symantec for the Windows CLI. Please see screenshot below.

![errorinstallation](https://user-images.githubusercontent.com/3241327/38383849-29ff961e-3940-11e8-9d63-8ad01edbe403.JPG)

We are not on authority to mark the application as a false positive since our workstation is inheriting the server policy. Can you check if this can be addressed?

**Comment by theSoenke** [comment] 2018-04-06 09:29
Hi @peterbetos thanks for reporting it. I will look into and check what we can do about this

**Comment by theSoenke** [comment] 2018-04-06 10:16
Could you maybe send me the version you are trying to use? Are you using the latest version 1.6.1?

**Comment by peterbetos** [comment] 2018-04-10 06:45
The Virus Definition on our workstations is up to date. Please see screenshot below:

![symantec](https://user-images.githubusercontent.com/3241327/38540158-8aa1204c-3ccd-11e8-8994-764c1d139e57.JPG)
Can you check why the executable is classified as WS.Reputation.1 score on Symantec? 
https://www.symantec.com/security_response/writeup.jsp?docid=2010-051308-1854-99

Is this something that needs to be contested on Symantec to flag with a better classification?

**Comment by theSoenke** [comment] 2018-04-11 11:13
I just got a confirmation from Symantec that the file will be whitelisted. According to them it takes up to 24 hours until it is whitelisted via Live Update

**Comment by peterbetos** [comment] 2018-04-11 13:46
Thanks. We'll leave this open till tomorrow until it's reflected that the CLI is whitelisted. :)

**Comment by peterbetos** [comment] 2018-04-13 03:57
I am now able to download the .exe file correctly. Closing this. Thanks.

**Comment by theSoenke** [comment] 2018-04-13 07:37
Great. Thanks for the confirmation!

**Comment by peterbetos** [comment] 2019-08-13 11:27
Hi Team - Symantec tagged the latest [phraseapp_windows_amd64.exe](https://github.com/phrase/phraseapp-client/releases/download/1.15.0/phraseapp_windows_amd64.exe) as false positive again. :(

**Comment by theSoenke** [comment] 2019-08-13 15:26
Thanks for letting us know. I will try to report this to Symantec again so they can update their signatures

**Comment by theSoenke** [comment] 2019-08-16 10:57
I've submitted the binary to Symantec but they were unable to reproduce the issue
> We have been unable to reproduce the detection issue described in your submission. Our investigation shows that the software you submitted is known-good and as such does not trigger any detections.

**Comment by theSoenke** [comment] 2019-08-19 09:39
@peterbetos Are you using `Symantec Endpoint Protection 12.x`  or `Symantec Endpoint Protection 14.x`?

**Comment by peterbetos** [comment] 2019-08-20 08:25
It's 14

![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/3241327/63330852-1c93b200-c367-11e9-9e62-b137bc98ebed.png)

**Comment by theSoenke** [comment] 2019-08-23 13:38
Thanks. That is interesting. I've reported the false positive for this version and got the message from above that they could not reproduce it. Not sure what we can do from our side about this

**Comment by theSoenke** [comment] 2020-03-20 14:26
@peterbetos Is there still an issue with Symantec and the client detected as a false positive? I'm closing this issue for now. But please let me know if it should come up again

**Closed by theSoenke** 2020-03-20 14:26 UTC
